# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-26 01:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tags', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='Noticia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('url', models.URLField()),
                ('thumbnail', models.URLField(blank=True, null=True)),
                ('created_utc', models.DateTimeField()),
                ('tags', models.ManyToManyField(to='tags.Tag')),
            ],
        ),
    ]
