# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-26 19:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tags', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Noticia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_reddit', models.CharField(blank=True, max_length=200, null=True)),
                ('title', models.CharField(max_length=200)),
                ('url', models.URLField(max_length=255)),
                ('thumbnail', models.URLField(blank=True, max_length=255, null=True)),
                ('created_utc', models.DateTimeField()),
                ('selftext', models.TextField(blank=True, null=True)),
                ('tags', models.ManyToManyField(to='tags.Tag')),
            ],
        ),
    ]
