# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-27 11:45
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('noticias', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='noticia',
            options={'ordering': ['-id']},
        ),
    ]
